### ISSUE TITLE
Impossible to create instance with any database with separated containers

### ISSUE THREAD

**Issue by raphaelcasimir** [crramirez/limesurvey#37]
Hello,
I tried to create a docker-compose instance like you suggest on your main readme, in order to separate containers and use volumes.

However when I tried to use mysql I got the same problem as #32 . I also tried to modify the docker-compose to get a lower version of mysql but in this case the container keeps restarting and is unusable.

I then tried pgsql, the docker processes seem to start OK but when completing the admin user creation this gets throwed and it is impossible to continue.

Thanks in advance if you take the time to solve these issues.

```
Could not add administrator settings: exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42703]: Undefined column: 7 ERROR: column d.adsrc does not exist LINE 1: ...ER(format_type(a.atttypid, a.atttypmod)) AS type, d.adsrc, a... ^' in /app/framework/db/CDbCommand.php:543 Stack trace: #0 /app/framework/db/CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array) #1 /app/framework/db/schema/pgsql/CPgsqlSchema.php(181): CDbCommand->queryAll() #2 /app/framework/db/schema/pgsql/CPgsqlSchema.php(113): CPgsqlSchema->findColumns(Object(CPgsqlTableSchema)) #3 /app/framework/db/schema/CDbSchema.php(103): CPgsqlSchema->loadTable('lime_users') #4 /app/framework/db/ar/CActiveRecord.php(2389): CDbSchema->getTable('{{users}}') #5 /app/framework/db/ar/CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(User)) #6 /app/framework/db/ar/CActiveRecord.php(682): CActiveRecord->getMetaData() #7 /app/application/models/LSActiveRecord.php(34): CActiveRecord->hasAttribute('created') #8 /app/framework/db/ar/CActiveRecord.php(398): LSActiveRecord->behaviors() #9 /app/application/models/User.php(53): CActiveRecord::model('User') #10 /app/application/controllers/InstallerController.php(594): User::model() #11 /app/application/controllers/InstallerController.php(87): InstallerController->stepOptionalConfiguration() #12 /app/framework/web/CWebApplication.php(282): InstallerController->run('optional') #13 /app/framework/web/CWebApplication.php(141): CWebApplication->runController('installer/optio...') #14 /app/framework/base/CApplication.php(185): CWebApplication->processRequest() #15 /app/index.php(194): CApplication->run() #16 {main}.
```

**Comment by crramirez** [comment]
Hello,

I will check

**Comment by raphaelcasimir** [comment]
Thanks a lot

**Comment by rbeier** [comment]
Hi,
any updates on this?

**Comment by crramirez** [comment]
Sorry I haven't had time. I am going to check it this weekend

**Comment by crramirez** [comment]
Well the problem is that the plugin for PHP installed in the image is not compatible with MySQL 8. As with limesurvey 4 I need to redo the image to support the latest ubuntu and php7. For now I limited the version for MySQL to 5 in the docker-compose.yml:

```yml
...
services:
  mysql:
    image: mysql:5
    volumes:
      - mysql:/var/lib/mysql
    restart: always
...
```

You must delete everything in order for this change work in your containers with:

```bash
docker-compose down --volumes
```

Regards,
Carlos

**Comment by jazari-akuna** [comment]
Thanks a lot for the support, I used another survey tool this time but I am sure it will be useful for others and for me in the future.

Just so you know there is probably still an issue with PostGreSQL.

@rbeier feel free to close the issue if you don't have more questions and everything works on your side

**Comment by rbeier** [comment]
Hi Carlos,
thanks for your support. It's working now. 

Greetings
Robin
